# Generated by Django 4.0.1 on 2022-01-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BigIntegerField(help_text="Doctor's appointment id")),
                ('patient_id', models.BigIntegerField(help_text="Patient's appointment id")),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Appointment created and waiting for status change'), ('ABSENT', "Patient's absent"), ('PERFORMED', 'The appointment was performed successfully'), ('CANCELLED', 'The appointment was cancelled by the doctor or patient')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointment',
                'ordering': ('-created_at',),
            },
        ),
    ]
